// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4c2pPGncB9YhDJiSbh6okzfK59PjfAw',
    appId: '1:590418953408:web:dac6e6571998af7035d925',
    messagingSenderId: '590418953408',
    projectId: 'trafficteststart419',
    authDomain: 'trafficteststart419.firebaseapp.com',
    storageBucket: 'trafficteststart419.firebasestorage.app',
    measurementId: 'G-44XPZRLH92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvK52K7MAMpFd1a95y-j0wR97m7-GWpQ',
    appId: '1:590418953408:android:9886ab701e6fb33a35d925',
    messagingSenderId: '590418953408',
    projectId: 'trafficteststart419',
    storageBucket: 'trafficteststart419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1VLsxB1W2TelvdteN8z2InFnMAWscjM',
    appId: '1:590418953408:ios:d116f4f76e872baf35d925',
    messagingSenderId: '590418953408',
    projectId: 'trafficteststart419',
    storageBucket: 'trafficteststart419.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf1VLsxB1W2TelvdteN8z2InFnMAWscjM',
    appId: '1:590418953408:ios:d116f4f76e872baf35d925',
    messagingSenderId: '590418953408',
    projectId: 'trafficteststart419',
    storageBucket: 'trafficteststart419.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX4c2pPGncB9YhDJiSbh6okzfK59PjfAw',
    appId: '1:590418953408:web:a0ec90bc042600f035d925',
    messagingSenderId: '590418953408',
    projectId: 'trafficteststart419',
    authDomain: 'trafficteststart419.firebaseapp.com',
    storageBucket: 'trafficteststart419.firebasestorage.app',
    measurementId: 'G-73M4CZVW7H',
  );
}
